version: '3.8'

services:
  #TODO: try replace with docker swarm secrets instead https://github.com/eerotal/certbot-docker-swarm
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ${DATA_ROOT}/certbot/www:/var/www/certbot:rw
      - ${DATA_ROOT}/certbot/conf:/etc/letsencrypt:rw
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    command:
      # --test-cert # Obtain a test certificate from a staging server
      # --dry-run # Perform a test run against the Let's Encrypt staging server, obtaining test (invalid) certificates but not saving them to disk
      certonly
      --webroot
      --webroot-path=/var/www/certbot
      --non-interactive
      --agree-tos
      --domain ${SERVER_NAME}
      --keep-until-expiring
      --test-cert
