version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      # using 'host' mode now to simplify diagnostics
      # * https://stackoverflow.com/questions/49415595/docker-swarm-get-real-ip-client-host-in-nginx
      # * to-do: custom http balancer for X-Real-IP 
      #- "8080:80"
      - mode: host
        protocol: tcp
        published: 8080
        target: 80
    volumes:
      - ./pages:/usr/share/nginx/html
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
