name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    #branches: [ 'master' ]
    paths:
      - '.github/workflows/deploy.yml'

jobs:
#  echo_job:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Echo Message
#        run: echo "Hello, this is a manually triggered workflow!"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #name: Checkout codebase

      - name: Setup SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.REMOTE_PRIVATE_KEY }}

      - name: Deploy Docker Stack
#          echo "==== key is added"
#          ssh-add -L
#          echo "==== check host available"
#          nc -vz ${{ secrets.REMOTE_HOST }} 22
#          echo "==== verify SSH (w/o host check)"
#          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} whoami
#          echo "==== verify SSH (w/ host check)"
#          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} whoami
#          echo "==== check known_hosts"
#          cat ~/.ssh/known_hosts
        run: |
          echo "==== setup known_hosts"
          ssh-keyscan -t rsa,ecdsa,ed25519 -H ${{ secrets.REMOTE_HOST }} 2> /dev/null >> ~/.ssh/known_hosts
          echo "==== docker stack deploy"
          DOCKER_HOST="ssh://${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}"
          docker -H $DOCKER_HOST stack deploy --compose-file docker-compose.yml tt

#      - name: Deploy stack
#        uses: shockhs/docker-stack-deploy@v1.2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}          
#          remote_host: ${{ secrets.REMOTE_HOST }}
#          remote_user: ${{ secrets.REMOTE_USER }}
#          remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
#          stack_file: "docker-compose.yml"
#          stack_name: "tt"
#          debug: 1
